// One reviewed list drives command recognition, validation and the workshop reference table.
// All finite events own their helper props and release them after the performance.
const event=(id,word,meaning,aliases,result,example,prop=null)=>({id,word,meaning,aliases,result,example,prop});
export const BEHAVIOR_ACTIONS = [
  event('push','push','推',['push','pushes','pushing','推'],'角色接近并把目标沿地面推开；只说物品时直接推动它。','让机器人推球'),
  event('pull','pull','拉',['pull','pulls','pulling','拉'],'目标与角色一起后移，结束后保留移动的位置。','让机器人拉盒子'),
  event('throw','throw','扔',['throw','throws','throwing','扔','抛'],'球从角色身旁沿抛物线飞出，落地回弹；缺球自动补球。','让企鹅扔球','rword-ball'),
  event('kick','kick','踢',['kick','kicks','kicking','踢'],'角色轻倾触球，球沿地面滚出；缺球自动补球。','让机器人踢球','rword-ball'),
  event('hide','hide','躲藏',['hide','hides','hiding','躲藏','躲起来'],'补一个遮挡盒，角色移到盒子后方、偶尔探头，再回到原位；盒子自动收起。','让海龟躲起来','rword-box'),
  event('swim','swim','游泳',['swim','swims','swimming','游泳'],'缺少水池时补小水池；游动结束后水池收起，原对象保留。','让小猫游泳','swimming-pool'),
  event('sail','sail','航行',['sail','sails','航行'],'优先使用指定船或飞机；缺少载具时补飞机，乘坐巡游后返回。','让小猫航行','airplane'),
  event('ride','ride','骑乘',['ride','rides','骑车','骑上','骑乘'],'缺少载具时补自行车；乘坐移动后回到原位。','让小熊骑车','rword-bike'),
  event('skate','skate','滑行',['skate','skates','滑冰','滑行'],'出现冰面，沿冰面滑动后收起。','让小猫滑冰','swimming-pool'),
  event('leap','leap','跃过',['leap','leaps','跃过','跨跳'],'越过小木头后落地。','让青蛙跃过木头','rword-log'),
  event('hop','hop','蹦跳',['hop','hops','单脚跳','蹦跳'],'有停顿的连续小跳；不强行改变无腿模型。','让小猫单脚跳'),
  event('zip','zip','快速移动',['zip','zips','快速移动','冲过去'],'短距离冲刺并留下速度线。','让小猫快速移动'),
  event('sit','sit','坐',['sit','sits','坐下','坐着'],'缺少座位时补座椅，用降身与坐姿符号表达。','让小熊坐下','rword-seat'),
  event('open','open','打开',['open','opens','打开'],'用开合展示罩露出指定物件；盒子、书和门补充打开提示。','打开盒子'),
  event('get','get / got','得到／接住',['get','got','gets','拿来','接住','得到'],'物品移到接取者面前并亮起确认符号。','让小猫接住球','rword-ball'),
  event('take','take','拿取',['take','takes','拿起','取走'],'将指定物品带到身旁；缺物品时补一个球。','让小猫拿起球','rword-ball'),
  event('tap','tap','轻敲',['tap','taps','轻敲','敲一敲','轻拍'],'小槌敲击目标，弹出节奏圈和音符。','轻敲铃铛','rword-bell'),
  event('clean','clean','清洁',['clean','cleans','打扫','弄干净','清洁'],'自动补抹布，擦去演示污点与湿润状态。','把小猫弄干净','rword-rag'),
  event('rip','rip','撕开',['rip','rips','撕开'],'纸片包装从中间分开，露出目标。','撕开包裹里的玩具'),
  event('dip','dip','蘸',['dip','dips','蘸一下','蘸'],'补颜料罐，物件蘸入后下端附着颜色。','让面包蘸一下颜料','rword-pot'),
  event('sip','sip','小口喝',['sip','sips','小口喝','喝一口'],'补饮料瓶，靠近嘴边并显示液面下降。','让小猫小口喝','rword-bottle'),
  event('dig','dig','挖',['dig','digs','挖坑','挖一挖','挖'],'补工具，土块移开露出坑与宝物。','让小狗挖坑','rword-tool'),
  event('mix','mix','混合',['mix','mixes','混合','搅拌'],'补调色盘，两团颜色汇合成新颜色；完成后对象变成混合色。','混合红色和黄色','rword-pan'),
  event('knit','knit','编织',['knit','knits','编织'],'毛线卷缩小，编织成一条围巾。','让小猫编织','rword-yarn'),
  event('bake','bake','烘烤',['bake','bakes','烘烤','烤蛋糕'],'补小烤箱，面团变成蛋糕后端出来。','让小熊烘烤蛋糕','rword-cake'),
  event('pop','pop','弹出',['pop','pops','弹出'],'目标从临时盒子里弹出来。','让小猫弹出来','rword-box'),
  event('draw','draw','画画',['draw','draws','画画'],'补画板与笔，逐笔画出一朵花。','让小猫画画','rword-pen'),
  event('play','play','玩／演奏',['play','plays','演奏','玩球'],'有球就玩球，有乐器就显示敲击与音符；默认补铃铛。','让小熊演奏铃铛','rword-bell'),
  event('read','read','阅读',['read','reads','阅读','读书'],'补一本书，文字条逐行亮起并翻页。','让小熊读书','rword-book'),
  event('look','look','看',['look','looks','看一看','看看','注视'],'眼睛符号和光圈指向目标。','让小猫看看花','rword-flower'),
  event('guess','guess','猜',['guess','guesses','猜一猜','猜猜'],'问号与遮罩隐藏目标，几秒后揭晓；这是猜物演示。','猜猜盒子里的玩具','rword-toy'),
  event('help','help','帮助',['help','helps','帮助','帮一帮'],'默认把被围住的目标解救出来；目标会抬升并出现爱心。','让小熊帮助小猫','rword-cat'),
  event('pay','pay','付款',['pay','pays','付款'],'补游戏金币，金币交给目标后出现确认符号。','让小熊付款','gold-coin'),
  event('look-out','look out','当心',['look out','当心','小心'],'警告符号亮起，目标侧身躲开滚来的球。','让小猫当心','rword-ball'),
];
export const BEHAVIOR_EFFECTS = [
  event('cold','cold','冷的',['cold','冷的','很冷','变冷'],'出现蓝色雪花与轻颤，和 hot 热气形成对照。','让企鹅变冷'),
  event('hungry','hungry','饿的',['hungry','饿了','饿的','饥饿'],'出现食物想象泡泡；可以继续说 eat 指定食物。','让刺猬饿了'),
  event('thirsty','thirsty','渴的',['thirsty','渴了','渴的','口渴'],'出现水滴想象泡泡；可以继续说 sip 来喝水。','让海龟渴了'),
  event('dirty','dirty','脏的',['dirty','脏的','弄脏','变脏'],'泥点贴在模型表面，clean 清除泥点。','把帐篷弄脏'),
  event('hum','hum','哼唱',['hum','hums','哼唱','哼歌'],'头顶飘动音符，不需要嘴型或真实演唱。','让小猫哼唱'),
  event('sleep','sleep','睡觉',['sleep','sleeps','睡觉','打盹'],'头顶飘 Z 字符，轻微呼吸；不强制模型躺倒。','让小猫睡觉'),
  event('sleepy','sleepy','困倦',['sleepy','困了','困倦','困'],'困倦表情与小 Z 字符。','让小猫变得困倦'),
  event('wet','wet','湿的',['wet','湿的','淋湿','变湿'],'身上挂水滴，短暂补水盆；水盆收起后保留湿润效果。','把小猫淋湿'),
  event('dry','dry','干的',['dry','干的','弄干','干燥'],'水滴消失，并收起自动补充的水盆。','把小猫弄干'),
  event('hot','hot','热的',['hot','热的','烫'],'头顶冒热气符号。','让锅变热'),
  event('yummy','yummy','好吃的',['yummy','好吃','美味'],'头顶爱心和满意表情。','让蛋糕变得好吃'),
  event('new','new','新的',['new','新的','崭新'],'物体亮起星星光泽，表示崭新。','让玩具焕然一新'),
  event('same','same','相同的',['same','相同','一样'],'将后一个对象的颜色和大小同步给前一个。','让小猫和小熊一样'),
];
export const BEHAVIOR_REFERENCE = [
  {title:'动作事件 · 缺少道具会自动补齐',rows:BEHAVIOR_ACTIONS},
  {title:'符号与状态 · 可与其他动作组合',rows:BEHAVIOR_EFFECTS},
  {title:'已有的通用动作与属性',rows:[
    event('move','go / walk / run','走／跑',[],'在原位置附近走动或跑动；stop 停止。','让小猫跑起来'),
    event('jump','jump','跳',[],'原地跳跃，可叠加大小和颜色。','让便便跳起来'),
    event('fly','fly','飞',[],'悬浮飞行，任意物件都适用。','让花飞起来'),
    event('roll','roll','滚',[],'旋转滚动。','让毛线滚动'),
    event('eat','eat','吃',[],'接近指定食物，咀嚼后消耗。','让小猫吃面包'),
    event('stop','stop','停止',[],'停止动作，清理自动道具；原有物件保留。','让小猫停下'),
    event('size','big / long / tall','大小和形状',[],'整体变大、拉长或长高；局部变化需指定部件。','让尾巴变长'),
    event('color','red / blue / yellow / green','颜色',[],'改变指定物体的颜色。','让小猫变蓝色'),
    event('mood','happy / sad / angry / funny','情绪',[],'头顶表情；滑稽状态附加摇摆。','让小猫开心'),
  ]},
];
