const ace = {
  id: "ace",
  type: "owl",
  name: "阿策",
  color: "#bfa98c",
  voice: "moss",
};
const friend = (characterId, name, voice = "bubble") => ({
  id: characterId,
  characterId,
  name,
  voice,
});
const scenes = [
  [
    "moon-observatory",
    "把问题做出来",
    "observatory",
    1,
    friend("baozai", "包仔"),
    "宇宙里的光回来了，可是还有好多问题没人试过。",
    "上一站，我们练习听不同的理由。这一站，让你的想法真的动起来。",
    "你想给好奇心救援队造什么？可以说样子、颜色，也可以请一个朋友帮忙。",
    ["一艘蓝色小火箭", "一座彩虹桥", "请豆芽做一个机器人"],
  ],
  [
    "moon-reef",
    "让海底朋友也能探索",
    "reef",
    1,
    friend("elfie", "Elfie"),
    "水边的朋友也想出发，可它们还没有适合自己的工具。",
    "造一艘小船、一台观察镜，或者你想出来的新东西。造好后我们一起试。",
    "你想造什么，让这里的朋友发现新的东西？",
    ["有窗户的探险小船", "能观察气泡的望远镜", "欢迎朋友的气泡喷泉"],
  ],
  [
    "moon-pocket",
    "不同点子拼在一起",
    "pocket",
    2,
    friend("landou", "蓝豆"),
    "这里收着大家用剩的布、木块和亮亮的纽扣。",
    "一个点子不够用，就拼两个。你的发明也可以改颜色、加伙伴。",
    "你想把哪些东西放在一起，让它们做点新事情？",
    ["会开门的图书小屋", "花园旁边的秋千", "请孙悟空来试折叠梯"],
  ],
  [
    "moon-cloud",
    "给安静的问题一个位置",
    "cloud",
    2,
    friend("hatty", "Hatty"),
    "有的朋友说得很轻，它们的问题飘进云里就听不见了。",
    "我们可以造个能见面、能停下来听的地方。你来决定它长什么样。",
    "你想造什么，让每个朋友都愿意说出自己的问题？",
    ["会亮灯的好奇小屋", "能轮流表演的音乐台", "带大家见面的传送门"],
  ],
  [
    "moon-landing",
    "月球好奇心广场",
    "moon",
    3,
    friend("allie", "Allie"),
    "月球上有一块空地，正好装下大家还没试过的想法。",
    "你可以造建筑、植物、工具，也可以请故事里的朋友来这里做事。",
    "这片广场先出现什么？它会给朋友带来什么新发现？",
    ["请铃铛照看的花园", "请猪小弟经营的点心台", "和咕噜一起试飞的火箭"],
  ],
  [
    "moon-arrival",
    "世界还在等你的下一件作品",
    "moon",
    3,
    friend("sage", "Sage"),
    "看，你造的东西都留下来了，朋友们正围着它们试。",
    "拯救好奇心，不是把所有问题答完。是有人愿意继续问、继续做。",
    "还想给这个世界加什么？也可以给刚才的作品加一个新部件。",
    ["花园边再加一座桥", "一台拍下新发现的相机", "请小鹿老师来弹钢琴"],
  ],
];
export const MOON_CURIOSITY_STORY = {
  id: "moon",
  version: 1,
  interaction: "creation",
  exploration: true,
  title: "登月计划 · 好奇心造物场",
  subtitle: "把问题变成作品，让朋友试出新的发现。",
  onboarding: "direct",
  age: "第三章 · 自由创造",
  companion: "rabbit",
  companionName: "小航",
  color: "#9799bd",
  premise:
    "第一束光让宇宙醒来，不同的理由让问题长大。现在轮到你：把想法做出来，留在这个世界里。",
  events: [
    {
      id: "try-a-new-idea",
      on: "creation.saved",
      effects: [
        {
          type: "actor.animate",
          target: "ace",
          animation: "wave",
          expression: "happy",
        },
      ],
    },
  ],
  chapters: [
    { number: 1, title: "从一个点子开始" },
    { number: 2, title: "让不同想法相遇" },
    { number: 3, title: "一起建造好奇心广场" },
  ],
  scenes: scenes.map(
    (
      [id, title, world, chapter, guest, first, second, question, suggestions],
      i,
    ) => ({
      id,
      title,
      world,
      chapter,
      objective: "创造一件能让朋友发现新事物的作品。",
      cast: [ace],
      dialogue: [
        { speaker: ace.id, text: first },
        { speaker: "companion", text: second },
      ],
      question,
      questionSpeaker: ace.id,
      freeInput: true,
      creation: true,
      interaction: "creation",
      inputMode: "voice",
      inventionSpeaker: ace.id,
      choices: suggestions.map((label, j) => ({
        id: `create-${i}-${j}`,
        label,
      })),
      closing: [],
      final: i === scenes.length - 1,
    }),
  ),
  ending: {
    title: "宇宙有了继续好奇的地方",
    text: "你的作品留在星球上。随时回来，找朋友试用，再加上新的点子。",
    companionLine:
      "好奇心的光没有停在这里。你下一个想问的问题，就是新旅程的起点。",
  },
};
