import assert from 'node:assert/strict';
import * as THREE from '../../vendor/three.module.js';
import {createFeedingController} from '../presentation/feeding-controller.js';
import {WorldRuntime} from '../runtime/world-runtime.js';
const entries=new Map();
const make=(position=[0,0])=>({entrance:2,position,contactRadius:.15,rest:new THREE.Vector3(0,5,0),normal:new THREE.Vector3(0,1,0),orientation:new THREE.Quaternion(),anchor:new THREE.Group()});
let consumed=[];
const stage={reduced:false,world:{surfaceNormal:(x,z)=>new THREE.Vector3(x,5,z).normalize(),planet:{center:new THREE.Vector3(),radius:5}}};
const feeding=createFeedingController({entries,stage,consume:(eater,food)=>{assert.ok(entries.has(food));entries.delete(food);consumed.push({eater,food});return {ok:true};}});
entries.set('pig',make());entries.set('burger',make());feeding.start(['pig'],['burger']);
for(let i=0;i<6;i++)feeding.update(.1,i*.1);
assert.equal(consumed.length,0);assert.equal(feeding.stats.jobs[0].bites,1);
for(let i=0;i<7;i++)feeding.update(.1,.6+i*.1);
assert.equal(consumed.length,1);feeding.update(.1,2);assert.equal(feeding.stats.active,0);
feeding.clear();entries.clear();consumed=[];
for(let i=0;i<10;i++)entries.set('pig'+i,make([i*.2,0]));
for(let i=0;i<80;i++)entries.set('food'+i,make([i%10*.2,Math.floor(i/10)*.2]));
feeding.start(Array.from({length:10},(_,i)=>'pig'+i),Array.from({length:80},(_,i)=>'food'+i));
feeding.update(.1,0);assert.equal(new Set(feeding.stats.claims.map(([food])=>food)).size,10);
for(let i=1;i<1000 && feeding.stats.active;i++)feeding.update(.1,i*.1);
assert.equal(consumed.length,80);assert.equal(new Set(consumed.map(x=>x.food)).size,80);assert.equal(feeding.stats.active,0);assert.equal(feeding.stats.claims.length,0);
entries.set('food-stop',make([8,8]));feeding.start(['pig0'],['food-stop']);feeding.update(.1,0);feeding.stop(['pig0']);feeding.update(.1,1);assert.ok(entries.has('food-stop'));
feeding.start(['pig1'],['food-stop']);entries.delete('pig1');feeding.update(.1,2);assert.equal(feeding.stats.active,0);assert.equal(feeding.stats.claims.length,0);
feeding.clear();
const runtime=new WorldRuntime();runtime.enter({storyId:'test',sceneId:'feeding',world:'meadow',actors:[]});
const spawn=(id,asset)=>({type:'entity.spawn',id,asset,position:[0,0]});
assert.ok(runtime.dispatch([spawn('pig','npc:zhuxiaodi'),spawn('food','prop:burger'),{type:'feeding.start',eaters:['pig'],foods:['food']}]).ok);
const before=JSON.stringify(runtime.snapshot);
assert.equal(runtime.dispatch([spawn('rock','prop:car'),{type:'feeding.start',eaters:['pig'],foods:['rock']}]).ok,false);
assert.equal(JSON.stringify(runtime.snapshot),before);
assert.equal(runtime.dispatch([{type:'feeding.start',eaters:['food'],foods:['pig']}]).ok,false);
assert.equal(runtime.dispatch([{type:'feeding.start',eaters:['pig','pig'],foods:['food']}]).ok,false);
assert.ok(runtime.dispatch([{type:'entity.scale',id:'pig',scale:1.95},{type:'entity.color',id:'pig',color:'#528ccc'}]).ok);
const restored=new WorldRuntime({saved:runtime.snapshot});assert.equal(restored.snapshot.worlds.meadow.entities.pig.scale,1.95);assert.equal(restored.snapshot.worlds.meadow.entities.pig.sizeLocked,true);assert.equal(restored.snapshot.worlds.meadow.entities.pig.colorOverride,true);
console.log('PASS: two bites per food, 10 eaters / 80 exclusive targets, stop/removal cleanup, atomic validation and edible constraints');
